---
  - name: "Installing system packages."
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"

  - name: "Ensure required services are running."
    service:
      name: "{{ item }}"
      state: "started"
    with_items: "{{ services }}"

  - name: "Enabling apache2 additional modules."
    apache2_module:
      name: "{{ item }}"
      state: present
    with_items: "{{ apache2_modules }}"
    notify: "Restart apache2"
